### PR TITLE
SQL script exported

### PR DESCRIPTION
**Pull request by Cobollatin**
Added complete functionality with the language keys. I haven't tested all tables individually but works when exporting all and exporting the biggest. The purpose is to use the SQL scripts for Azerothcore, so there is a current column fix that runs when the script is exported, the tables that have a fix are the spell and spellvisual tables. Next steps are to find a way to only select the rows that had been updated since the session started (or a checkpoint) and optimize the post process of the SQL script.

Also added windows resize when changing the tab in the Import/Export window.

image
image
image

### CODE REVIEW

**Comment by stoneharry** [comment]
Thank you for the PR! You made my morning, I always love when people contribute to the project. This looks like it will be incredibly useful.

I will do a deep dive on the code later today.

**Comment by Cobollatin** [comment]
No worries. Please do not merge get, I am adding the table adapters for the default tables. The user said those are the only ones he loads.

**Comment by stoneharry** [comment]
Some things I noticed from a very quick test:
- The progress bars do not report the %, they jump from 0% to 100% 
- I think we should change the export type from the dropdown rather than having another button. The current `Export Checked to DBC Files` button can be renamed to `Export Checked`
- Some of the file diffs are showing changes on the entire file for some reason, which makes it hard to read.

I can help out once you are happy with it.

**Comment by Cobollatin** [comment]
The bars appear but they are just too quick. 
image
I do agree with the second point, but it will require refactoring existing functionality. If that's fine with you then I will go ahead.
This may be because visual studio reformats the project file when adding a library.

I am almost done; I will gladly accept your help; do you mind having a conversation on Discord?

**Comment by Cobollatin** [comment]
The bars appear but they are just too quick. 
image
I do agree with the second point, but it will require refactoring existing functionality. If that's fine with you then I will go ahead.
This may be because visual studio reformats the project file when adding a library.

I am almost done; I will gladly accept your help, do you mind having a conversation on discord?

**Comment by stoneharry** [comment]
Sure my Discord is just `stoneharry`

**Comment by stoneharry** [comment]
Whops. I did not mean to merge this yet. I must have accidentally pressed it. Going to revert from master but please do re-open the PR. I will continue working on it too.

**Pull request merged**
